### ISSUE TITLE
Allow configuration management of templates via YAML 

### ISSUE THREAD

**Issue by rovangju** [oliverisaac/tgrep#5]
As roughly outlined in #2  - we could add a way to manage both the templates and the tests through a YAML config file instead of directly in Go. This would allow an easy path to extensibility.

Proposed schema example:

```
schemaVer: 1
templates:
- name: ipv4
  template: ([1334].regex)
  description: "Match normal IPV4 values"
  tests:
  - it: "Should match 4 octets"
    passingInputs:
      - "0.0.0.0"
      - "0.0.0.1"
    failingInputs:
      - "256.0.0.1"
      - "1.0.0.0.1"
      - "shit"
      - "one.two.three.four"
```
